import Img from './images/articles/blogImg01.jpg';
import Img02 from './images/articles/blogImg02.jpg';
import Img03 from './images/articles/blogImg03.jpg';
import Img04 from './images/articles/blogImg04.jpg';
import Img05 from './images/articles/blogImg05.jpg';
import Img06 from './images/articles/blogImg06.jpg';
import post01 from './images/articles/PopPost01.jpg';
import post02 from './images/articles/PopPost02.jpg';
import site01 from './images/site/site01.jpg';
import site02 from './images/site/site02.jpg';
import site03 from './images/site/site03.jpg';
import site04 from './images/site/site04.jpg';
import site05 from './images/site/site05.jpg';
import site06 from './images/site/site06.jpg';
import site07 from './images/site/site07.jpg';
import site08 from './images/site/site08.jpg';

const blog01 = document.getElementById('blog01');
const blog02 = document.getElementById('blog02');
const blog03 = document.getElementById('blog03');
const blog04 = document.getElementById('blog04');
const blog05 = document.getElementById('blog05');
const blog06 = document.getElementById('blog06');
const PopPost01 = document.getElementById('popPost01');
const PopPost02 = document.getElementById('popPost02');
const sitePic01 = document.getElementById('sitePic01');
const sitePic02 = document.getElementById('sitePic02');
const sitePic03 = document.getElementById('sitePic03');
const sitePic04 = document.getElementById('sitePic04');
const sitePic05 = document.getElementById('sitePic05');
const sitePic06 = document.getElementById('sitePic06');
const sitePic07 = document.getElementById('sitePic07');
const sitePic08 = document.getElementById('sitePic08');

blog01.src = Img;
blog02.src = Img02;
blog03.src = Img03;
blog04.src = Img04;
blog05.src = Img05;
blog06.src = Img06;
PopPost01.src = post01;
PopPost02.src = post02;
sitePic01.src = site01;
sitePic02.src = site02;
sitePic03.src = site03;
sitePic04.src = site04;
sitePic05.src = site05;
sitePic06.src = site06;
sitePic07.src = site07;
sitePic08.src = site08;